services:
  orchestration:
    build: ./services/orchestration
    ports:
      - "8000:8000"
    # depends_on:
    #   - transcription
    #   - agent
    # environment:
    #   - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-southeast-1}
    #   - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    #   - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      # - ~/.aws:/root/.aws:ro
      - ./services/orchestration/app:/app
    command: >
      sh -c "
      uv sync --directory /app && 
      uv run --directory /app main.py
      "    
  transcription:
    build: ./services/transcription
    ports:
      - "8001:8001"
    volumes:
      - ./services/transcription/app:/app
    command: >
      sh -c "
      uv sync --directory /app && 
      uv run --directory /app main.py
      "    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

  agent:
    build: ./services/agent
    ports:
      - "8002:8002"
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-southeast-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./services/agent/app:/app
    command: >
      sh -c "
      uv sync --directory /app && 
      uv run --directory /app main.py
      "    

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - orchestration
