services:
  backend-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-southeast-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}      
    stdin_open: true
    tty: true
    # command: /bin/bash
    # command: uv run --directory /app/backend main.py 
    command: >
      sh -c "
      uv sync --directory /app/backend && 
      uv run --directory /app/backend main.py
      "    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia  # For backward compatibility if needed
    restart: unless-stopped    
